name = "ManyThread"
uuid = "e03a0512-6b8f-41a5-bdf7-a90df6cc3ad9"
authors = ["emmac <emmacboudreau@gmail.com>"]
version = "0.1.0"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Toolips = "a47e2ad8-fcf7-417c-9746-32b9bdf220bd"
